import json

with open("could-gemma4-playing-hamurabi.ipynb", "r") as f:
    nb = json.load(f)

for cell in nb["cells"]:
    if cell["cell_type"] == "code" and "from transformers import TextStreamer" in "".join(cell["source"]):
        source = [
            "import re\n",
            "import time\n",
            "import os\n",
            "from IPython.display import display, HTML, clear_output\n",
            "\n",
            "MAX_GENERATIONS = 3\n",
            "\n",
            "# Dynasty Loop\n",
            "for generation in range(1, MAX_GENERATIONS + 1):\n",
            "    # Initialize the game logic\n",
            "    game = HamurabiGame()\n",
            "    \n",
            "    # Refresh System Prompt to include any newly written metamemory from the previous generation\n",
            "    metamemory_addition = \"\"\n",
            "    if os.path.exists(\"metamemory.txt\"):\n",
            "        with open(\"metamemory.txt\", \"r\") as f:\n",
            "            past_lessons = f.read()\n",
            "        metamemory_addition = f\"\\n\\nPAST LIVES METAMEMORY (Learn from past mistakes):\\n{past_lessons}\\n\"\n",
            "\n",
            "    SYSTEM_PROMPT = f\"\"\"You are the Grand Vizier of Babylon. \n",
            "    I will provide you with a 'REPORT' containing raw data. \n",
            "    1. Think silently about the implications of the data (famine, rats, events).\n",
            "    2. Present the stats in a narrative way, evaluating the kingdom's health.\n",
            "    3. You are making the decisions. Decide how many acres to buy/sell, how much to feed the people, and how much to plant.\n",
            "    At the very end of your response, you MUST provide your final decrees in EXACTLY this format:\n",
            "    DECISION_BUY: [number] (use negative to sell)\n",
            "    DECISION_FEED: [number]\n",
            "    DECISION_PLANT: [number]\n",
            "\n",
            "    THE LAWS OF BABYLON (GAME MECHANICS):\n",
            "    Before making your decrees, you MUST calculate your budget in your thought block using these exact rules:\n",
            "    1. FEEDING: 1 person requires exactly 20 bushels to survive the year. If you feed them less, people will starve.\n",
            "    2. PLANTING: It costs exactly 0.5 bushels of seed to plant 1 acre of land. You cannot plant more acres than you own.\n",
            "    3. REAL ESTATE: Buying 1 acre costs the current 'Land Value' in bushels. Selling 1 acre (using a negative number for DECISION_BUY) ADDS the 'Land Value' in bushels to your total available budget.\n",
            "    4. THE GOLDEN RULE: (Bushels spent on Buying Land) + (Bushels spent on Feeding) + (Bushels spent on Planting) MUST NOT exceed your total available Bushels (which includes any Bushels gained from Selling Land).\n",
            "    5. WISE RULER: BUY LOW SELL HIGH is a mantra if needed more Bushels resources, but don't neglect the peoples. A wise leader is know when to selling land but not oversell your land for bushels that you lose ability to planting.\n",
            "    6. TRADING RULE: Low is when price is below 20. High is when price is above 20. But don't oversell your land. you need to plantation to help the grow of your resources.{metamemory_addition}\"\"\"\n",
            "\n",
            "    # Main Game Loop\n",
            "    messages = [{\"role\": \"system\", \"content\": SYSTEM_PROMPT}]\n",
            "\n",
            "    while not game.game_over:\n",
            "        raw_data = game.get_slm_payload()\n",
            "        \n",
            "        # Add the current year's status to the conversation history\n",
            "        messages.append({\"role\": \"user\", \"content\": f\"Current Kingdom Status:\\n{raw_data}\"})\n",
            "        \n",
            "        decree_accepted = False\n",
            "        \n",
            "        # The AI Retry Loop\n",
            "        while not decree_accepted:\n",
            "            text = processor.apply_chat_template(messages, tokenize=False, add_generation_prompt=True, enable_thinking=True)\n",
            "            inputs = processor(text=text, return_tensors=\"pt\").to(model.device)\n",
            "            input_len = inputs[\"input_ids\"].shape[-1]\n",
            "            \n",
            "            outputs = model.generate(**inputs, max_new_tokens=4096)\n",
            "            \n",
            "            # Decode with skip_special_tokens=False to keep <|think|> tags\n",
            "            full_response = processor.decode(outputs[0][input_len:], skip_special_tokens=False)\n",
            "            \n",
            "            # Parse the response\n",
            "            result = processor.parse_response(full_response)\n",
            "            thoughts = result.get(\"thinking\", \"No reasoning provided.\")\n",
            "            content = result.get(\"content\", \"\")\n",
            "            \n",
            "            # Display the UI\n",
            "            event_html = f\"<div style='color: #d9534f; font-weight: bold;'>Event: {game.current_event['desc']}</div>\" if game.current_event else \"\"\n",
            "            \n",
            "            ui_html = f\"\"\"\n",
            "            <div style=\"font-family: sans-serif; max-width: 800px; margin: 20px auto; border: 1px solid #ccc; border-radius: 8px; overflow: hidden; box-shadow: 0 4px 8px rgba(0,0,0,0.1);\">\n",
            "                <div style=\"background-color: #f8f9fa; padding: 15px; border-bottom: 1px solid #eee; display: flex; justify-content: space-between; align-items: center;\">\n",
            "                    <h2 style=\"margin: 0; color: #333;\">Babylon Chronicles: Year {game.year}</h2>\n",
            "                    <span style=\"background-color: #0056b3; color: white; padding: 5px 10px; border-radius: 12px; font-size: 0.8em; font-weight: bold;\">Dynasty Generation {generation} of {MAX_GENERATIONS}</span>\n",
            "                </div>\n",
            "                <div style=\"padding: 15px;\">\n",
            "                    <div style=\"display: grid; grid-template-columns: repeat(2, 1fr); gap: 10px; margin-bottom: 15px;\">\n",
            "                        <div style=\"background: #e9ecef; padding: 10px; border-radius: 4px; color: #333;\"><strong>Population:</strong> {game.population}</div>\n",
            "                        <div style=\"background: #e9ecef; padding: 10px; border-radius: 4px; color: #333;\"><strong>Acres:</strong> {game.acres}</div>\n",
            "                        <div style=\"background: #e9ecef; padding: 10px; border-radius: 4px; color: #333;\"><strong>Bushels:</strong> {game.bushels}</div>\n",
            "                        <div style=\"background: #e9ecef; padding: 10px; border-radius: 4px; color: #333;\"><strong>Land Value:</strong> {game.land_value}</div>\n",
            "                        <div style=\"background: #f8d7da; padding: 10px; border-radius: 4px; color: #721c24;\"><strong>Rats:</strong> {game.eaten_by_rats}</div>\n",
            "                        <div style=\"background: #f8d7da; padding: 10px; border-radius: 4px; color: #721c24;\"><strong>Starved:</strong> {game.died_of_starvation}</div>\n",
            "                    </div>\n",
            "                    {event_html}\n",
            "                </div>\n",
            "                \n",
            "                <details style=\"margin: 15px; background: #fdfdfd; border: 1px solid #ddd; padding: 10px; border-radius: 4px;\">\n",
            "                    <summary style=\"cursor: pointer; font-weight: bold; color: #0056b3;\">Click to view Vizier's Reasoning (Thinking Mode)</summary>\n",
            "                    <pre style=\"white-space: pre-wrap; font-size: 0.9em; margin-top: 10px; color: #555;\">{thoughts}</pre>\n",
            "                </details>\n",
            "                \n",
            "                <div style=\"padding: 15px; background-color: #f1f8ff; border-top: 1px solid #eee;\">\n",
            "                    <h3 style=\"margin-top: 0; color: #0366d6;\">Vizier's Decrees</h3>\n",
            "                    <pre style=\"white-space: pre-wrap; font-size: 1em; color: #24292e;\">{content}</pre>\n",
            "                </div>\n",
            "            </div>\n",
            "            \"\"\"\n",
            "            clear_output(wait=True)\n",
            "            display(HTML(ui_html))\n",
            "            \n",
            "            try:\n",
            "                buy_sell = int(re.search(r\"DECISION_BUY:\\s*(-?\\d+)\", content).group(1))\n",
            "                feed = int(re.search(r\"DECISION_FEED:\\s*(\\d+)\", content).group(1))\n",
            "                plant = int(re.search(r\"DECISION_PLANT:\\s*(\\d+)\", content).group(1))\n",
            "                \n",
            "                # --- THE CALCULATOR CHECK ---\n",
            "                is_valid, accountant_message = game.check_decree(buy_sell, feed, plant)\n",
            "                \n",
            "                if is_valid:\n",
            "                    display(HTML(f\"<div style='margin: 0 auto; max-width: 800px; padding: 10px; background: #d4edda; color: #155724; border-radius: 4px;'>[SYSTEM] {accountant_message} Executing Decrees...</div><br>\"))\n",
            "                    game.play_turn(buy_sell, feed, plant)\n",
            "                    # Append the parsed final content to the history, STRIPPING the thoughts\n",
            "                    messages.append({\"role\": \"assistant\", \"content\": content})\n",
            "                    decree_accepted = True # Breaks the inner loop, moves to next year\n",
            "                else:\n",
            "                    display(HTML(f\"<div style='margin: 0 auto; max-width: 800px; padding: 10px; background: #fff3cd; color: #856404; border-radius: 4px;'>[SYSTEM] {accountant_message}<br>[SYSTEM] Forcing Vizier to recalculate...</div><br>\"))\n",
            "                    \n",
            "                    # Append the AI's failed attempt to the history (without thoughts to save context)\n",
            "                    messages.append({\"role\": \"assistant\", \"content\": content})\n",
            "                    # Append the calculator's error message so the AI can read it and try again\n",
            "                    messages.append({\"role\": \"user\", \"content\": accountant_message})\n",
            "                    \n",
            "            except (AttributeError, ValueError):\n",
            "                display(HTML(\"<div style='margin: 0 auto; max-width: 800px; padding: 10px; background: #f8d7da; color: #721c24; border-radius: 4px;'>[SYSTEM WARNING] The Vizier's decrees were illegible! Forcing a rewrite...</div><br>\"))\n",
            "                messages.append({\"role\": \"assistant\", \"content\": content})\n",
            "                messages.append({\"role\": \"user\", \"content\": \"ACCOUNTANT ERROR: You failed to use the exact DECISION format at the end of your response. Please rewrite your decree.\"})\n",
            "        \n",
            "        time.sleep(1)\n",
            "\n",
            "    final_html = f\"\"\"\n",
            "    <div style=\"font-family: sans-serif; max-width: 800px; margin: 40px auto; padding: 20px; text-align: center; background: #343a40; color: white; border-radius: 8px;\">\n",
            "        <h1 style=\"margin-top: 0;\">The Reign of Hammurabi has ended after {game.year - 1} years.</h1>\n",
            "        <h2 style=\"color: #ffc107;\">Final Population: {game.population} | Final Acres: {game.acres}</h2>\n",
            "    </div>\n",
            "    \"\"\"\n",
            "    display(HTML(final_html))\n",
            "\n",
            "    # --- METAMEMORY REFLECTION ---\n",
            "    reflection_prompt = \"\"\"The reign has ended. As the outgoing Grand Vizier, reflect on your entire playthrough.\\n\"\n",
            "    \"1. Analyze your successes and failures (did people starve? did you lose land? did you balance the budget correctly?).\\n\"\n",
            "    \"2. Formulate 3 distinct, concise rules or lessons learned that the NEXT Vizier should follow to avoid your mistakes.\\n\"\n",
            "    \"3. Decide whether to pass these lessons to a new Dynasty and play again. Output REPLAY: YES or REPLAY: NO.\\n\"\n",
            "    \"Format your final output exactly as follows:\\n\"\n",
            "    \"LESSON 1: [Text]\\n\"\n",
            "    \"LESSON 2: [Text]\\n\"\n",
            "    \"LESSON 3: [Text]\\n\"\n",
            "    \"REPLAY: [YES/NO]\"\"\"\n",
            "\n",
            "    messages.append({\"role\": \"user\", \"content\": reflection_prompt})\n",
            "    text = processor.apply_chat_template(messages, tokenize=False, add_generation_prompt=True, enable_thinking=True)\n",
            "    inputs = processor(text=text, return_tensors=\"pt\").to(model.device)\n",
            "    input_len = inputs[\"input_ids\"].shape[-1]\n",
            "    outputs = model.generate(**inputs, max_new_tokens=2048)\n",
            "\n",
            "    full_response = processor.decode(outputs[0][input_len:], skip_special_tokens=False)\n",
            "    result = processor.parse_response(full_response)\n",
            "    reflection_thoughts = result.get(\"thinking\", \"No reasoning provided.\")\n",
            "    reflection_content = result.get(\"content\", \"\")\n",
            "\n",
            "    # Extract lessons and save to metamemory\n",
            "    lessons = []\n",
            "    for line in reflection_content.split('\\n'):\n",
            "        if line.startswith(\"LESSON\"):\n",
            "            lessons.append(line.strip())\n",
            "\n",
            "    if lessons:\n",
            "        metamemory_text = \"\\n\".join(lessons)\n",
            "    else:\n",
            "        metamemory_text = reflection_content\n",
            "\n",
            "    with open(\"metamemory.txt\", \"w\") as f:\n",
            "        f.write(metamemory_text)\n",
            "\n",
            "    replay_decision = \"YES\" if \"REPLAY: YES\" in reflection_content else \"NO\"\n",
            "\n",
            "    reflection_html = f\"\"\"\n",
            "    <div style=\"font-family: sans-serif; max-width: 800px; margin: 20px auto; border: 1px solid #4a148c; border-radius: 8px; overflow: hidden; box-shadow: 0 4px 8px rgba(0,0,0,0.1);\">\n",
            "        <div style=\"background-color: #f3e5f5; padding: 15px; border-bottom: 1px solid #e1bee7;\">\n",
            "            <h2 style=\"margin: 0; color: #4a148c;\">Metamemory Reflection</h2>\n",
            "        </div>\n",
            "        <details style=\"margin: 15px; background: #fdfdfd; border: 1px solid #ddd; padding: 10px; border-radius: 4px;\">\n",
            "            <summary style=\"cursor: pointer; font-weight: bold; color: #0056b3;\">Click to view Vizier's Reflection Process</summary>\n",
            "            <pre style=\"white-space: pre-wrap; font-size: 0.9em; margin-top: 10px; color: #555;\">{reflection_thoughts}</pre>\n",
            "        </details>\n",
            "        <div style=\"padding: 15px; background-color: #fafafa;\">\n",
            "            <h3 style=\"margin-top: 0; color: #333;\">Lessons for the Next Generation:</h3>\n",
            "            <pre style=\"white-space: pre-wrap; font-size: 1em; color: #24292e;\">{reflection_content}</pre>\n",
            "            <div style=\"margin-top: 10px; font-style: italic; color: #2e7d32;\">These lessons have been saved to metamemory.txt and will guide the next agent!</div>\n",
            "            <div style=\"margin-top: 10px; font-weight: bold; color: #c62828;\">The Vizier's Replay Decision: {replay_decision}</div>\n",
            "        </div>\n",
            "    </div>\n",
            "    \"\"\"\n",
            "    display(HTML(reflection_html))\n",
            "\n",
            "    if replay_decision == \"NO\":\n",
            "        display(HTML(\"<div style='text-align: center; color: #666; font-style: italic; margin-top: 20px;'>The AI has chosen to end the Dynasty loop early.</div>\"))\n",
            "        break\n",
            "    else:\n",
            "        display(HTML(\"<div style='text-align: center; color: #0056b3; font-weight: bold; margin-top: 20px;'>A new Generation rises! Passing lessons to the next Vizier...</div>\"))\n",
            "        time.sleep(3)\n",
        ]
        cell["source"] = source

    if cell["cell_type"] == "code" and "SYSTEM_PROMPT = " in "".join(cell["source"]):
        cell["source"] = [] # Clear the old separate system prompt cell since we merged it

# remove empty cells
nb["cells"] = [c for c in nb["cells"] if len(c["source"]) > 0]

with open("could-gemma4-playing-hamurabi.ipynb", "w") as f:
    json.dump(nb, f, indent=1)
